apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
   {{- include "ledger.labels" . | nindent 4 }}
data:
  metrics_exporter: "none"
  otel_resource_attributes: "service.name=ledger"
  otel_otlp_endpoint: "http://jaeger-collector.observability:4317"
