apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.user }}
  password: {{ .Values.db.pass }}
  url: {{ .Values.db.url }}
  kafka_jaas: {{ .Values.kafka.jaas }}
